services:
  nerd-bot:
    build: .
    env_file: ../.env
  postgres:
    image: postgres:15
    restart: always
    shm_size: 128mb
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: